name: Num-Alpha Conversions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: denqiu/reusable-tools/.github/workflows/py-setup-test.yml@main
    with:
      version: 3.12
      install_file: requirements.txt
      test_folder: tests